# Generated by Django 6.0.7 on 2026-08-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название курса')),
                ('url', models.URLField(verbose_name='Ссылка на курс')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Ваше имя')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Ваш email')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Ваш Telegram')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
            ],
        ),
    ]
