# Generated by Django 6.1 on 2026-08-10 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suggestion',
            options={'verbose_name': 'Предложение курса', 'verbose_name_plural': 'Предложения курсов'},
        ),
    ]
