# Generated by Django 6.0.6 on 2026-07-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='author',
        ),
        migrations.AddField(
            model_name='course',
            name='authors',
            field=models.ManyToManyField(to='courses.author', verbose_name='Авторы'),
        ),
    ]
