# Generated by Django 6.0.6 on 2026-07-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_author_course_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='author',
            name='url',
            field=models.URLField(blank=True, verbose_name='Ссылка на автора'),
        ),
    ]
