# Generated by Django 6.0.7 on 2026-07-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_author_description_author_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="avatar",
            field=models.ImageField(
                blank=True, upload_to="authors/photos/", verbose_name="Фотография"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="courses/photos/", verbose_name="Фотография"
            ),
        ),
    ]
