# Generated by Django 6.0.7 on 2026-07-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_author_avatar_course_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="slug",
            field=models.SlugField(blank=True, max_length=130, verbose_name="Slug"),
        ),
    ]
